# Generated by Django 4.1.3 on 2024-06-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
