# Generated by Django 4.1.3 on 2024-06-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='email_address',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='first_name', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='house_number_street_name',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='last_name', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode_zip',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='town_city',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='card', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
    ]
