# Generated by Django 4.1.3 on 2024-06-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_orderitem_price_alter_orderitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='cart',
            new_name='order',
        ),
    ]
