# Generated by Django 4.1.3 on 2024-06-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_to_different_address',
            field=models.BooleanField(default=False),
        ),
    ]
