# Generated by Django 4.1.3 on 2024-06-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_order_create_account_order_ship_to_different_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='create_account',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_to_different_address',
        ),
    ]
