# Generated by Django 4.1.3 on 2024-06-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_remove_order_create_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
