# Generated by Django 4.1.3 on 2024-06-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_remove_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
