# Generated by Django 4.1.3 on 2024-06-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_remove_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
