# Generated by Django 4.1.3 on 2024-06-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_account',
            field=models.BooleanField(default=False),
        ),
    ]
