# Generated by Django 4.1.3 on 2024-06-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_remove_orderitem_product_order_created_order_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated',
        ),
    ]
