# Generated by Django 4.1.3 on 2024-06-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0025_order_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(default='Company_Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Country', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='email_address',
            field=models.EmailField(default='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='First_Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='house_number_street_name',
            field=models.CharField(default='House_Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Last_Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(default='Mobile', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Card', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode_zip',
            field=models.CharField(default='Post', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='Ghc', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='town_city',
            field=models.CharField(default='Town/City', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(default='Username', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default='Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
